### ISSUE TITLE
runtime: out of memory

### ISSUE THREAD

**Issue by seed1234** [galexrt/docker-sinusbot#18]
Task Name:

Docker container sinusbot exited with nonzero status.
Description:

Docker container sinusbot has exited with status 255

**Comment by galexrt** [comment]
On what architecture are you running Docker?

**Comment by seed1234** [comment]
how do i check the architecture ?

**Comment by galexrt** [comment]
To get the architecture of the system run `uname -a` and post the output here.

Also provide logs of the container by running `docker logs CONTAINER_ID` (the `CONTAINER_ID` can be seen by running `docker ps -a`).

**Comment by seed1234** [comment]
`Linux box 4.4.27-boot2docker #1 SMP Thu Mar 9 02:09:50 UTC 2017 x86_64 GNU/Linux`

**Comment by galexrt** [comment]
Please also provide logs of the container by running `docker logs CONTAINER_ID` (the `CONTAINER_ID` can be seen by running `docker ps -a`, the `CONTAINER_ID` is the name of the container).

**Comment by seed1234** [comment]
how do i enable ssh for boot2docker

**Comment by galexrt** [comment]
Run `boot2docker ssh` and then run `docker logs sinusbot` to get the logs. Post the logs here.

**Comment by seed1234** [comment]
-> Setting Sinusbot log file location to "" ...                                                                                                          
                                               => Sinusbot logging to "/sinusbot/data/sinus.log".                                                        
                                                                                                 -> Updating sinusbot user and group id if necessary ... 
                                                                                                                                                        -
> Correcting file and mount point permissions ...                                                                                                        
                                                 => Corrected mount point permissions.                                                                   
                                                                                      -> Checking if scripts directory is empty                          
                                                                                                                               => Scripts directory is ma
rked that scripts got copied. Nothing to do.                                                                                                             
                                            -> Checking for old data location ...                                                                        
                                                                                 => You are good to go! You are already using the new data directory, loc
ated at "/sinusbot/data".                                                                                                                                
                         => Updating Youtube-dl...                                                                                                       
                                                  youtube-dl is up-to-date (2017.03.10)                                                                  
                                                                                       => Updated youtube-dl with exit code 0                            
                                                                                                                             => Starting SinusBot (https:
//sinusbot.com) by Michael Friese ...

**Comment by galexrt** [comment]
@seed1234 Are you sure that this is the full output? The output you commented is full with tabs and spaces.

**Comment by seed1234** [comment]
```
-> Setting Sinusbot log file location to "" ...
=> Sinusbot logging to "/sinusbot/data/sinus.log".
-> Updating sinusbot user and group id if necessary ...
-> Correcting file and mount point permissions ...
=> Corrected mount point permissions.
-> Checking if scripts directory is empty
=> Scripts directory is marked that scripts got copied. Nothing to do.
-> Checking for old data location ...
=> You are good to go! You are already using the new data directory, located at "/sinusbot/data".
=> Updating Youtube-dl...
youtube-dl is up-to-date (2017.03.10)
=> Updated youtube-dl with exit code 0
=> Starting SinusBot (https://sinusbot.com) by Michael Friese ...
fatal error: runtime: out of memory

runtime stack:
�]�(_?�b�$[(0x197ca37)
        /usr/local/go/src/runtime/panic.go:491 +0xad
|%��<��m�˯�1(0xc208200000, 0x5dd00000, 0x1994300, 0x19a2e38)
        /usr/local/go/src/runtime/mem_linux.c:149 +0x98
F��sn:�>�!��=׼+oS��Z�(0x19a8520, 0x5dd00000, 0x89f142)
        /usr/local/go/src/runtime/malloc.c:284 +0x124
MHeap_Grow(0x19a8520, 0x2ee80, 0x0)
        /usr/local/go/src/runtime/mheap.c:398 +0x58
MHeap_AllocSpanLocked(0x19a8520, 0x2ee80, 0x7faa00000001)
        /usr/local/go/src/runtime/mheap.c:298 +0x365
mheap_alloc(0x19a8520, 0x2ee80, 0x100000000, 0x1994300)
        /usr/local/go/src/runtime/mheap.c:190 +0x121
��      �$�O�ާ���]�C8(0x19a8520, 0x2ee80, 0x10100000000, 0x7faa71465f70)
        /usr/local/go/src/runtime/mheap.c:240 +0x66
1!�Q�X�iت�5N7�q�Wa�()
        /usr/local/go/src/runtime/malloc.c:388 +0xce
������7�t(0x1994330)
        /usr/local/go/src/runtime/asm_amd64.s:257 +0x68
�H�ݼ�{�30v^*()
        /usr/local/go/src/runtime/proc.c:818

goroutine 1 [running]:
|d��u�P����C�C�()
        /usr/local/go/src/runtime/asm_amd64.s:198 fp=0xc2080a92e8 sp=0xc2080a92e0
k��j�B�*�?��n�(0x5dd00000, 0xf11d60, 0x1, 0xfc55f7f900000006)
        /usr/local/go/src/runtime/malloc.go:199 +0x9f3 fp=0xc2080a9398 sp=0xc2080a92e8
��"��7��,�N7
            (0xf11d60, 0x5dd00000, 0x9881c6)
        /usr/local/go/src/runtime/malloc.go:365 +0xc1 fp=0xc2080a93d0 sp=0xc2080a9398
��V��gh���v��g(0xef9360, 0x5dd00000, 0x5dd00000, 0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/slice.go:32 +0x15c fp=0xc2080a9418 sp=0xc2080a93d0
main.main()
        �͈Ϲ��8�n"
                 7�E��e˲贊&ϵs$t�B:433 +0x106a fp=0xc2080a9f98 sp=0xc2080a9418
/xzeB:�k0�_�()
        /usr/local/go/src/runtime/proc.go:63 +0xf3 fp=0xc2080a9fe0 sp=0xc2080a9f98
����$��<�M���6()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080a9fe8 sp=0xc2080a9fe0

goroutine 5 [runnable]:
text/template/parse.lexText(0xc20808e000, 0x1432cf8)
        /usr/local/go/src/text/template/parse/lex.go:228 +0x37b
text/template/parse.(*lexer).run(0xc20808e000)
        /usr/local/go/src/text/template/parse/lex.go:198 +0x5d
created by text/template/parse.lex
        /usr/local/go/src/text/template/parse/lex.go:191 +0x1ac

goroutine 6 [runnable]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:19
created by os/signal.init·1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
����$��<�M���6()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
-> Setting Sinusbot log file location to "" ...
=> Sinusbot logging to "/sinusbot/data/sinus.log".
-> Updating sinusbot user and group id if necessary ...
-> Correcting file and mount point permissions ...
=> Corrected mount point permissions.
-> Checking if scripts directory is empty
=> Scripts directory is marked that scripts got copied. Nothing to do.
-> Checking for old data location ...
=> You are good to go! You are already using the new data directory, located at "/sinusbot/data".
=> Updating Youtube-dl...
youtube-dl is up-to-date (2017.03.10)
=> Updated youtube-dl with exit code 0
=> Starting SinusBot (https://sinusbot.com) by Michael Friese ...
fatal error: runtime: out of memory

runtime stack:
�]�(_?�b�$[(0x197ca37)
        /usr/local/go/src/runtime/panic.go:491 +0xad
|%��<��m�˯�1(0xc208200000, 0x5dd00000, 0x1994300, 0x19a2e38)
        /usr/local/go/src/runtime/mem_linux.c:149 +0x98
F��sn:�>�!��=׼+oS��Z�(0x19a8520, 0x5dd00000, 0x89f142)
        /usr/local/go/src/runtime/malloc.c:284 +0x124
MHeap_Grow(0x19a8520, 0x2ee80, 0x0)
        /usr/local/go/src/runtime/mheap.c:398 +0x58
MHeap_AllocSpanLocked(0x19a8520, 0x2ee80, 0x7f5700000001)
        /usr/local/go/src/runtime/mheap.c:298 +0x365
mheap_alloc(0x19a8520, 0x2ee80, 0x100000000, 0x1994300)
        /usr/local/go/src/runtime/mheap.c:190 +0x121
��      �$�O�ާ���]�C8(0x19a8520, 0x2ee80, 0x10100000000, 0x7f578b818f70)
        /usr/local/go/src/runtime/mheap.c:240 +0x66
1!�Q�X�iت�5N7�q�Wa�()
        /usr/local/go/src/runtime/malloc.c:388 +0xce
������7�t(0x1994330)
        /usr/local/go/src/runtime/asm_amd64.s:257 +0x68
�H�ݼ�{�30v^*()
        /usr/local/go/src/runtime/proc.c:818

goroutine 1 [running]:
|d��u�P����C�C�()
        /usr/local/go/src/runtime/asm_amd64.s:198 fp=0xc2080cf2e8 sp=0xc2080cf2e0
k��j�B�*�?��n�(0x5dd00000, 0xf11d60, 0x1, 0xfc55f7f900000006)
        /usr/local/go/src/runtime/malloc.go:199 +0x9f3 fp=0xc2080cf398 sp=0xc2080cf2e8
��"��7��,�N7
            (0xf11d60, 0x5dd00000, 0x9881c6)
        /usr/local/go/src/runtime/malloc.go:365 +0xc1 fp=0xc2080cf3d0 sp=0xc2080cf398
��V��gh���v��g(0xef9360, 0x5dd00000, 0x5dd00000, 0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/slice.go:32 +0x15c fp=0xc2080cf418 sp=0xc2080cf3d0
main.main()
        �͈Ϲ��8�n"
                 7�E��e˲贊&ϵs$t�B:433 +0x106a fp=0xc2080cff98 sp=0xc2080cf418
/xzeB:�k0�_�()
        /usr/local/go/src/runtime/proc.go:63 +0xf3 fp=0xc2080cffe0 sp=0xc2080cff98
����$��<�M���6()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080cffe8 sp=0xc2080cffe0

goroutine 6 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
����$��<�M���6()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
docker@box:~$ B
```

**Comment by galexrt** [comment]
As you can see from the logs it seems that one of components (sinusbot, docker runtime) ran out of memory.
How much memory is allocated to the boot2docker instance?

**Comment by seed1234** [comment]
in the boot2 docker it says 2GiB which is 2.147483648GB

**Comment by galexrt** [comment]
What does `docker info` output in the boot2docker instance?

**Comment by seed1234** [comment]
```
Containers: 14
 Running: 11
 Paused: 0
 Stopped: 3
Images: 79
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 161
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: macvlan host null overlay bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.27-boot2docker
Operating System: Boot2Docker 1.12.3 (TCL 7.2); master : bd7bcc1 - Thu Mar  9 03:10:11 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: box
ID: DIDW:5DQE:7G4A:GFPQ:FY6A:75J7:62K6:5IOR:UFVM:BIWX:UKN3:QGBQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 79
 Goroutines: 114
 System Time: 2017-03-11T17:04:57.81261654Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Comment by galexrt** [comment]
Run `free` and `free -h` in the boot2docker instance.

**Comment by seed1234** [comment]
```
docker@box:~$ free
              total        used        free      shared  buff/cache   available
Mem:        2050368     1446464       95744      151256      508160      256564
Swap:        443108      395440       47668
docker@box:~$ free -h
              total        used        free      shared  buff/cache   available
Mem:           2.0G        1.4G         92M        147M        496M        249M
Swap:          432M        386M         46M
docker@box:~$
```

**Comment by galexrt** [comment]
@seed1234 I hope you see for yourself what the problem is now.. There is not enough memory (and swap) free.
From the `docker info` output I see that you there are already 11 containers running, that just seems to be too much for the small system you are running Docker (the boot2docker instance) on.

**Comment by seed1234** [comment]
Okay i have set up another instance  boot2docker and i installed sinusbot
It works now 

Thanks for your help
